global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # OTEL Collector metrics
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8888"]
    scrape_interval: 10s
    metrics_path: /metrics

  # OTEL Collector exported metrics (from applications)
  - job_name: "otel-exported-metrics"
    static_configs:
      - targets: ["otel-collector:8889"]
    scrape_interval: 10s
    metrics_path: /metrics

  # Backend service (if exposing metrics directly)
  - job_name: "backend"
    static_configs:
      - targets: ["backend:8080"]
    metrics_path: /metrics
    scrape_interval: 10s

  # PostgreSQL metrics (using postgres_exporter if added)
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres:5432"]
    scrape_interval: 30s

  # Redis metrics (using redis_exporter if added)
  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
    scrape_interval: 30s

  # Node exporter for system metrics (if added)
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
