receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
    send_batch_max_size: 2048

  memory_limiter:
    limit_mib: 512
    check_interval: 1s

  resource:
    attributes:
      - key: service.name
        value: file-dedup-service
        action: upsert
      - key: service.version
        value: 0.1.0
        action: upsert

exporters:
  # Export metrics to Prometheus via HTTP endpoint (pull-based)
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      service: "file-dedup-otel-collector"
    resource_to_telemetry_conversion:
      enabled: true

  # Export logs to Loki via OTLP HTTP
  otlphttp/loki:
    endpoint: http://loki:3100/otlp/v1/logs
    headers:
      "Content-Type": "application/x-protobuf"

  # Export traces to Jaeger (optional - can be added later)
  # jaeger:
  #   endpoint: jaeger:14250
  #   tls:
  #     insecure: true

  # Debug exporter for debugging (replaces deprecated logging exporter)
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [debug]

    metrics:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [prometheus, debug]

    logs:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [otlphttp/loki, debug]

  extensions: []
